# Security-related response headers

add_header Access-Control-Allow-Origin   $acao_policy     always;
add_header Referrer-Policy               $referrer_policy always;
add_header Timing-Allow-Origin           '*'              always;
add_header X-Content-Type-Options        nosniff          always;
add_header X-Frame-Options               $x_frame_options always;

add_header Content-Security-Policy       $cs_policy       always;
add_header Cross-Origin-Embedder-Policy  $coe_policy      always;
add_header Cross-Origin-Opener-Policy    $coo_policy      always;
add_header Cross-Origin-Resource-Policy  $cor_policy      always;
add_header Permissions-Policy            $perm_policy     always;

# add_header Strict-Transport-Security   "max-age=86400;  includeSubDomains" always;
