    # include limits.conf;                 # connection and request rate limits
    # include autoindex_off.conf;          # disable directory listing
    # include force_https.conf;            # enforce HTTPS
    # include force_non_www.conf;          # redirect www → non-www
    # include block_hidden_files.conf;     # block hidden files and folders
    # include block_sensitive_files.conf;  # block backup/config/log files
    # include strip_query_string.conf;     # remove query strings
    # include quiet_static_logs.conf;      # disable logs for favicon/robots
    # include fallback_redirect.conf;      # fallback to index.php
    # include brotli.conf;                 # enable and configure brotli compression
    # include gzip.conf;                   # enable and configure gzip compression
    # include maintenance_mode.conf;       # enable site-wide maintenance mode

    # include security_headers.conf;       # add standard security headers for static fhost
    # include expires_headers.conf;        # set caching headers for static fhost

    index index.html index.htm;
