    # include limits.conf;                 # connection and request rate limits
    # include autoindex_off.conf;          # disable directory listing
    # include force_https.conf;            # enforce HTTPS
    # include force_non_www.conf;          # redirect www → non-www
    # include block_hidden_files.conf;     # block hidden files and folders
    # include block_sensitive_files.conf;  # block backup/config/log files
    # include strip_query_string.conf;     # remove query strings
    # include quiet_static_logs.conf;      # disable logs for favicon/robots
    # include brotli.conf;                 # enable and configure brotli compression
    # include gzip.conf;                   # enable and configure gzip compression
    # include maintenance_mode.conf;       # enable site-wide maintenance mode

    # include security_fcgi_headers.conf;  # add security headers for fastcgi host
    # include expires_fcgi_headers.conf;   # set caching headers for fastcgi host

    # include fallback_redirect.conf;      # fallback to index.php

    index         index.php index.html index.htm;
    fastcgi_index index.php;

    location ~ \.php$ {
        fastcgi_pass $backend_ip:$backend_port;
        try_files    $fastcgi_script_name =404;
        include      fastcgi.conf;
        # fastcgi_param  COUNTRY_CODE    $geoip2_data_country_code;
        # fastcgi_param  COUNTRY_NAME    $geoip2_data_country_name;
    }
