    location / {
        proxy_http_version    1.1;
        proxy_cache_bypass    $http_upgrade $cookie_nocache $arg_nocache $http_pragma $http_authorization;
        proxy_ssl_server_name on;
        proxy_pass            http://$backend_ip:$backend_port;
        proxy_redirect        http://$backend_ip:$backend_port/ /;
        proxy_set_header      Upgrade           $http_upgrade;
        proxy_set_header      Connection        $connection_upgrade;
        proxy_set_header      Host              $host;
        proxy_set_header      Accept-Encoding   "";
        proxy_set_header      X-Real-IP         $remote_addr;
        proxy_set_header      Forwarded         $proxy_add_forwarded;
        proxy_set_header      X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header      X-Forwarded-Proto $scheme;
        proxy_set_header      X-Forwarded-Host  $host;
        proxy_set_header      X-Forwarded-Port  $server_port;
        # proxy_set_header    X-Country-Code    $geoip2_data_country_code;
        # proxy_set_header    X-Country-Name    $geoip2_data_country_name;
    }

    # include limits.conf;                 # connection and request rate limits
    include   autoindex_off.conf;          # disable directory listing
    # include force_https.conf;            # enforce HTTPS
    # include force_non_www.conf;          # redirect www → non-www
    # include block_hidden_files.conf;     # block hidden files and folders
    # include block_sensitive_files.conf;  # block backup/config/log files
    # include strip_query_string.conf;     # remove query strings
    # include quiet_static_logs.conf;      # disable logs for favicon/robots
    # include fallback_redirect.conf;      # fallback to index.php
    # include brotli.conf;                 # enable and configure brotli compression
    # include gzip.conf;                   # enable and configure gzip compression
    # include maintenance_mode.conf;       # enable site-wide maintenance mode

    # include security_proxy_headers.conf; # add security headers for proxy host
    # include expires_proxy_headers.conf;  # set caching headers for proxy host
