# Maintenance mode page

if (-f $document_root/maintenance.html) {
    set $lang mt.$lang;
    return 503;
}

if (-f $document_root/maintenance.txt) {
    set $lang mt.$lang;
    return 503;
}

if (-f $document_root/maintenance.flag) {
    set $lang mt.$lang;
    return 503;
}